# Generated by Django 3.2.16 on 2023-03-04 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='сolor',
            new_name='kolor',
        ),
    ]
