# Generated by Django 3.2.16 on 2022-11-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221113_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopIngredientList',
        ),
    ]
