# Generated by Django 3.2.16 on 2023-03-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_kolor_tag_сolor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients_Recipe',
            new_name='IngredientsRecipe',
        ),
    ]
