# Generated by Django 3.2.16 on 2022-11-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='array',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
